spring:
  profiles:
    active: local
    include:
      - domain
token:
  access_token:
    expiration_time: 604800000 #30일
  secret: secret

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug